import { ALL_TIME_SLOTS } from '../data/timeSlots';
import { buildDosesForDay, formatClinicDate, getWeekDates, medDisplayName } from '../schedule';
import { findPreset } from '../data/medications';
import type { AppState } from '../types';

export function renderPrintSchedule(state: AppState): string {
  const week = getWeekDates(state.selectedDay || state.clinicDate);
  const days = week.length > 0 ? week : getWeekDates(new Date().toISOString().slice(0, 10));

  const slotRows = ALL_TIME_SLOTS.map((slot) => {
    const dayCells = days
      .map((day) => {
        const doses = buildDosesForDay(state, day.iso).filter((d) => d.slotId === slot.id);
        if (doses.length === 0) {
          return `<td class="print-cell print-cell--empty"></td>`;
        }
        const inner = doses
          .map((d) => {
            const oral = d.isOral ? ' <span class="print-oral">ORAL TABLET</span>' : '';
            return `
            <div class="print-dose">
              <span class="print-check-box" aria-hidden="true"></span>
              <span class="print-dose-text">
                <strong>${d.medName}${oral}</strong><br/>
                ${d.eyeLabel}
                ${d.notes ? `<br/><em>${d.notes}</em>` : ''}
              </span>
            </div>`;
          })
          .join('');
        return `<td class="print-cell">${inner}</td>`;
      })
      .join('');

    return `
      <tr>
        <th class="print-time-col">${slot.shortLabel}<br/><span class="print-time-sub">${slot.period}</span></th>
        ${dayCells}
      </tr>`;
  });

  const medLegend = state.medications
    .map((entry) => {
      const preset = findPreset(entry.presetId);
      const name = medDisplayName(entry);
      const oral = preset?.isOral ? ' (ORAL TABLET)' : '';
      const cap = preset?.isOral
        ? '💊'
        : `● Cap color: ${preset?.capColor ?? 'custom'}`;
      return `<li><strong>${name}</strong>${oral} — ${cap}</li>`;
    })
    .join('');

  return `
    <div id="print-area" class="print-area" aria-hidden="true">
      <header class="print-header">
        <h1>Glaucoma Medication Schedule</h1>
        <div class="print-meta-grid">
          <div class="print-meta-box">
            <span class="print-meta-label">Patient Name</span>
            <span class="print-meta-value">${state.patientName || '________________________'}</span>
          </div>
          <div class="print-meta-box">
            <span class="print-meta-label">Clinic Date</span>
            <span class="print-meta-value">${formatClinicDate(state.clinicDate) || '________________________'}</span>
          </div>
        </div>
        <div class="print-meta-box print-meta-box--wide">
          <span class="print-meta-label">Special Instructions</span>
          <span class="print-meta-value">${state.specialInstructions || '________________________________________________________________'}</span>
        </div>
      </header>

      ${
        medLegend
          ? `<section class="print-legend"><h2>Medications on this schedule</h2><ul>${medLegend}</ul></section>`
          : ''
      }

      <table class="print-week-table">
        <thead>
          <tr>
            <th class="print-time-col">Time</th>
            ${days.map((d) => `<th>${d.label}<br/><span class="print-day-sub">${d.short}</span></th>`).join('')}
          </tr>
        </thead>
        <tbody>${slotRows.join('')}</tbody>
      </table>

      <section class="print-daily-detail">
        <h2>Daily checklist (all days — same routine)</h2>
        ${ALL_TIME_SLOTS.map((slot) => {
          const doses = buildDosesForDay(state, state.selectedDay).filter(
            (d) => d.slotId === slot.id,
          );
          if (doses.length === 0) return '';
          return `
          <div class="print-daily-block">
            <h3>${slot.shortLabel} — ${slot.period}</h3>
            <ul>
              ${doses
                .map(
                  (d) => `
                <li class="print-daily-item">
                  <span class="print-check-box"></span>
                  <span><strong>${d.medName}</strong> — ${d.eyeLabel}${d.notes ? ` (${d.notes})` : ''}</span>
                </li>`,
                )
                .join('')}
            </ul>
          </div>`;
        }).join('')}
      </section>

      <footer class="print-footer">
        <p>Check each box with a pen when you have taken your drops. No patient health data is sent over the internet.</p>
        <p class="print-footer__small">Generated by Glaucoma Drop Calendar — for clinic use only. Not a substitute for medical advice.</p>
      </footer>
    </div>`;
}

export function triggerPrint(): void {
  window.print();
}
